export const StockList = {
  sku001: {
    skuCode: 'sku001',
    name: 'b/p tiger',
    boxValue: 108,
    box: 3,
    issue: 4,
  },
  sku002: {
    skuCode: 'sku002',
    name: 's/p tiger',
    boxValue: 108,
    box: 3,
    issue: 4,
  },
  sku003: {
    skuCode: 'sku003',
    name: 't/p prince',
    boxValue: 108,
    box: 3,
    issue: 4,
  },
  sku004: {
    skuCode: 'sku004',
    name: 'b/p tiger',
    boxValue: 108,
    box: 3,
    issue: 4,
  },
  sku005: {
    skuCode: 'sku005',
    name: 's/p tiger',
    boxValue: 108,
    box: 3,
    issue: 4,
  },
  sku006: {
    skuCode: 'sku006',
    name: 't/p prince',
    boxValue: 108,
    box: 3,
    issue: 4,
  },
  sku007: {
    skuCode: 'sku007',
    name: 'b/p tiger',
    boxValue: 108,
    box: 3,
    issue: 4,
  },
  sku008: {
    skuCode: 'sku008',
    name: 's/p tiger',
    boxValue: 108,
    box: 3,
    issue: 4,
  },
  sku009: {
    skuCode: 'sku009',
    name: 't/p prince',
    boxValue: 108,
    box: 3,
    issue: 4,
  },
  sku010: {
    skuCode: 'sku010',
    name: 't/p prince',
    boxValue: 108,
    box: 3,
    issue: 4,
  },
  sku011: {
    skuCode: 'sku011',
    name: 't/p prince',
    boxValue: 108,
    box: 3,
    issue: 4,
  },
  sku012: {
    skuCode: 'sku012',
    name: 't/p prince',
    boxValue: 108,
    box: 3,
    issue: 4,
  },
  sku013: {
    skuCode: 'sku0013',
    name: 't/p prince',
    boxValue: 108,
    box: 3,
    issue: 4,
  },
  sku014: {
    skuCode: 'sku014',
    name: 't/p prince',
    boxValue: 108,
    box: 3,
    issue: 4,
  },
  sku015: {
    skuCode: 'sku015',
    name: 't/p prince',
    boxValue: 108,
    box: 3,
    issue: 4,
  },
};
// [
//     {
//       name: 'b/p tiger',
//       boxValue: 108,
//       box: 3,
//       issue: 4,

//     },
//     {
//         name: 's/p tiger',
//         boxValue: 108,
//         box: 4,
//     },
//     {
//         name: 't/p prince',
//         boxValue: 108,
//         box: 5,
//     },
//     {
//         name: 'b/p prince',
//         boxValue: 108,
//         box: 6,
//     },
//     {
//         name: 's/p prince',
//         boxValue: 108,
//         box: 7,
//     },
//   ];
